//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGRS.AddOn.Purchases.TimbradoSoap33Prodigia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="timbrado.ws.pade.mx", ConfigurationName="TimbradoSoap33Prodigia.PadeTimbradoService")]
    public interface PadeTimbradoService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/cancelarRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/cancelarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarResponse cancelar(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/cancelarRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/cancelarResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarResponse> cancelarAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/cfdiPorUUIDRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/cfdiPorUUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDResponse cfdiPorUUID(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/cfdiPorUUIDRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/cfdiPorUUIDResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDResponse> cfdiPorUUIDAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbrado", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoResponse timbrado(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrado", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoResponse> timbradoAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbradoPrueba", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoPruebaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaResponse timbradoPrueba(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbradoPrueba", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoPruebaResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaResponse> timbradoPruebaAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="consultarEstatusComprobante", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/consultarEstatusComprobanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteResponse consultarEstatusComprobante(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarEstatusComprobante", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/consultarEstatusComprobanteResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteResponse> consultarEstatusComprobanteAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="consultarCfdiRelacionados", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/consultarCfdiRelacionadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosResponse consultarCfdiRelacionados(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarCfdiRelacionados", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/consultarCfdiRelacionadosResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosResponse> consultarCfdiRelacionadosAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/acuseCancelacionRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/acuseCancelacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionResponse acuseCancelacion(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/acuseCancelacionRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/acuseCancelacionResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionResponse> acuseCancelacionAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="responderSolicitudCancelacionConOpciones", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/responderSolicitudCancelacionConOpcionesR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesResponse responderSolicitudCancelacionConOpciones(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="responderSolicitudCancelacionConOpciones", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/responderSolicitudCancelacionConOpcionesR" +
            "esponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesResponse> responderSolicitudCancelacionConOpcionesAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/cancelarConOpcionesRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/cancelarConOpcionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesResponse cancelarConOpciones(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrado.ws.pade.mx/PadeTimbradoService/cancelarConOpcionesRequest", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/cancelarConOpcionesResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesResponse> cancelarConOpcionesAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbradoBase64Prueba", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoBase64PruebaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaResponse timbradoBase64Prueba(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbradoBase64Prueba", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoBase64PruebaResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaResponse> timbradoBase64PruebaAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="consultarPeticionesPendientes", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/consultarPeticionesPendientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesResponse consultarPeticionesPendientes(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarPeticionesPendientes", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/consultarPeticionesPendientesResponse")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesResponse> consultarPeticionesPendientesAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbradoBase64", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoBase64Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Response timbradoBase64(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbradoBase64", ReplyAction="timbrado.ws.pade.mx/PadeTimbradoService/timbradoBase64Response")]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Response> timbradoBase64Async(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelar", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class cancelarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arregloUUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] cert;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyPass;
        
        public cancelarRequest() {
        }
        
        public cancelarRequest(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.rfcEmisor = rfcEmisor;
            this.arregloUUID = arregloUUID;
            this.cert = cert;
            this.key = key;
            this.keyPass = keyPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class cancelarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cancelarResponse() {
        }
        
        public cancelarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorUUID", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid;
        
        public cfdiPorUUIDRequest() {
        }
        
        public cfdiPorUUIDRequest(string contrato, string usuario, string passwd, string uuid) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfdiPorUUIDResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class cfdiPorUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cfdiPorUUIDResponse() {
        }
        
        public cfdiPorUUIDResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbrado", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public timbradoRequest() {
        }
        
        public timbradoRequest(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXml = cfdiXml;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbradoResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public timbradoResponse() {
        }
        
        public timbradoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbradoPrueba", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoPruebaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public timbradoPruebaRequest() {
        }
        
        public timbradoPruebaRequest(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXml = cfdiXml;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbradoPruebaResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoPruebaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public timbradoPruebaResponse() {
        }
        
        public timbradoPruebaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstatusComprobante", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class consultarEstatusComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public consultarEstatusComprobanteRequest() {
        }
        
        public consultarEstatusComprobanteRequest(string contrato, string usuario, string passwd, string uuid, string rfcEmisor, string rfcReceptor, string total, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.rfcReceptor = rfcReceptor;
            this.total = total;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstatusComprobanteResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class consultarEstatusComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public consultarEstatusComprobanteResponse() {
        }
        
        public consultarEstatusComprobanteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCfdiRelacionados", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class consultarCfdiRelacionadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] cert;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public consultarCfdiRelacionadosRequest() {
        }
        
        public consultarCfdiRelacionadosRequest(string contrato, string usuario, string passwd, string rfcReceptor, string uuid, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.rfcReceptor = rfcReceptor;
            this.uuid = uuid;
            this.cert = cert;
            this.key = key;
            this.keyPass = keyPass;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCfdiRelacionadosResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class consultarCfdiRelacionadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public consultarCfdiRelacionadosResponse() {
        }
        
        public consultarCfdiRelacionadosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="acuseCancelacion", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class acuseCancelacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid;
        
        public acuseCancelacionRequest() {
        }
        
        public acuseCancelacionRequest(string contrato, string usuario, string passwd, string uuid) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="acuseCancelacionResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class acuseCancelacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public acuseCancelacionResponse() {
        }
        
        public acuseCancelacionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="responderSolicitudCancelacionConOpciones", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class responderSolicitudCancelacionConOpcionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arregloUUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] cert;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public responderSolicitudCancelacionConOpcionesRequest() {
        }
        
        public responderSolicitudCancelacionConOpcionesRequest(string contrato, string usuario, string passwd, string rfcReceptor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.rfcReceptor = rfcReceptor;
            this.arregloUUID = arregloUUID;
            this.cert = cert;
            this.key = key;
            this.keyPass = keyPass;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="responderSolicitudCancelacionConOpcionesResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class responderSolicitudCancelacionConOpcionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public responderSolicitudCancelacionConOpcionesResponse() {
        }
        
        public responderSolicitudCancelacionConOpcionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarConOpciones", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class cancelarConOpcionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arregloUUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] cert;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public cancelarConOpcionesRequest() {
        }
        
        public cancelarConOpcionesRequest(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.rfcEmisor = rfcEmisor;
            this.arregloUUID = arregloUUID;
            this.cert = cert;
            this.key = key;
            this.keyPass = keyPass;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarConOpcionesResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class cancelarConOpcionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cancelarConOpcionesResponse() {
        }
        
        public cancelarConOpcionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbradoBase64Prueba", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoBase64PruebaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXmlBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public timbradoBase64PruebaRequest() {
        }
        
        public timbradoBase64PruebaRequest(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXmlBase64 = cfdiXmlBase64;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbradoBase64PruebaResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoBase64PruebaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public timbradoBase64PruebaResponse() {
        }
        
        public timbradoBase64PruebaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPeticionesPendientes", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class consultarPeticionesPendientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public consultarPeticionesPendientesRequest() {
        }
        
        public consultarPeticionesPendientesRequest(string contrato, string usuario, string passwd, string rfcReceptor, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.rfcReceptor = rfcReceptor;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPeticionesPendientesResponse", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class consultarPeticionesPendientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public consultarPeticionesPendientesResponse() {
        }
        
        public consultarPeticionesPendientesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbradoBase64", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoBase64Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiXmlBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] opciones;
        
        public timbradoBase64Request() {
        }
        
        public timbradoBase64Request(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            this.contrato = contrato;
            this.usuario = usuario;
            this.passwd = passwd;
            this.cfdiXmlBase64 = cfdiXmlBase64;
            this.opciones = opciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbradoBase64Response", WrapperNamespace="timbrado.ws.pade.mx", IsWrapped=true)]
    public partial class timbradoBase64Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="timbrado.ws.pade.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public timbradoBase64Response() {
        }
        
        public timbradoBase64Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PadeTimbradoServiceChannel : UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PadeTimbradoServiceClient : System.ServiceModel.ClientBase<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService>, UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService {
        
        public PadeTimbradoServiceClient() {
        }
        
        public PadeTimbradoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PadeTimbradoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PadeTimbradoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PadeTimbradoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.cancelar(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest request) {
            return base.Channel.cancelar(request);
        }
        
        public string cancelar(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcEmisor = rfcEmisor;
            inValue.arregloUUID = arregloUUID;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).cancelar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.cancelarAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest request) {
            return base.Channel.cancelarAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarResponse> cancelarAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcEmisor = rfcEmisor;
            inValue.arregloUUID = arregloUUID;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).cancelarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.cfdiPorUUID(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest request) {
            return base.Channel.cfdiPorUUID(request);
        }
        
        public string cfdiPorUUID(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).cfdiPorUUID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.cfdiPorUUIDAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest request) {
            return base.Channel.cfdiPorUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDResponse> cfdiPorUUIDAsync(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cfdiPorUUIDRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).cfdiPorUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbrado(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest request) {
            return base.Channel.timbrado(request);
        }
        
        public string timbrado(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbrado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbradoAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest request) {
            return base.Channel.timbradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoResponse> timbradoAsync(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbradoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbradoPrueba(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest request) {
            return base.Channel.timbradoPrueba(request);
        }
        
        public string timbradoPrueba(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbradoPrueba(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbradoPruebaAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest request) {
            return base.Channel.timbradoPruebaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaResponse> timbradoPruebaAsync(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoPruebaRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXml = cfdiXml;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbradoPruebaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.consultarEstatusComprobante(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest request) {
            return base.Channel.consultarEstatusComprobante(request);
        }
        
        public string consultarEstatusComprobante(string contrato, string usuario, string passwd, string uuid, string rfcEmisor, string rfcReceptor, string total, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.rfcReceptor = rfcReceptor;
            inValue.total = total;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).consultarEstatusComprobante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.consultarEstatusComprobanteAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest request) {
            return base.Channel.consultarEstatusComprobanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteResponse> consultarEstatusComprobanteAsync(string contrato, string usuario, string passwd, string uuid, string rfcEmisor, string rfcReceptor, string total, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarEstatusComprobanteRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.rfcReceptor = rfcReceptor;
            inValue.total = total;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).consultarEstatusComprobanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.consultarCfdiRelacionados(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest request) {
            return base.Channel.consultarCfdiRelacionados(request);
        }
        
        public string consultarCfdiRelacionados(string contrato, string usuario, string passwd, string rfcReceptor, string uuid, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcReceptor = rfcReceptor;
            inValue.uuid = uuid;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).consultarCfdiRelacionados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.consultarCfdiRelacionadosAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest request) {
            return base.Channel.consultarCfdiRelacionadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosResponse> consultarCfdiRelacionadosAsync(string contrato, string usuario, string passwd, string rfcReceptor, string uuid, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarCfdiRelacionadosRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcReceptor = rfcReceptor;
            inValue.uuid = uuid;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).consultarCfdiRelacionadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.acuseCancelacion(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest request) {
            return base.Channel.acuseCancelacion(request);
        }
        
        public string acuseCancelacion(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).acuseCancelacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.acuseCancelacionAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest request) {
            return base.Channel.acuseCancelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionResponse> acuseCancelacionAsync(string contrato, string usuario, string passwd, string uuid) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.acuseCancelacionRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.uuid = uuid;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).acuseCancelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.responderSolicitudCancelacionConOpciones(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest request) {
            return base.Channel.responderSolicitudCancelacionConOpciones(request);
        }
        
        public string responderSolicitudCancelacionConOpciones(string contrato, string usuario, string passwd, string rfcReceptor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcReceptor = rfcReceptor;
            inValue.arregloUUID = arregloUUID;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).responderSolicitudCancelacionConOpciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.responderSolicitudCancelacionConOpcionesAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest request) {
            return base.Channel.responderSolicitudCancelacionConOpcionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesResponse> responderSolicitudCancelacionConOpcionesAsync(string contrato, string usuario, string passwd, string rfcReceptor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.responderSolicitudCancelacionConOpcionesRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcReceptor = rfcReceptor;
            inValue.arregloUUID = arregloUUID;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).responderSolicitudCancelacionConOpcionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.cancelarConOpciones(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest request) {
            return base.Channel.cancelarConOpciones(request);
        }
        
        public string cancelarConOpciones(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcEmisor = rfcEmisor;
            inValue.arregloUUID = arregloUUID;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).cancelarConOpciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.cancelarConOpcionesAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest request) {
            return base.Channel.cancelarConOpcionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesResponse> cancelarConOpcionesAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.cancelarConOpcionesRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcEmisor = rfcEmisor;
            inValue.arregloUUID = arregloUUID;
            inValue.cert = cert;
            inValue.key = key;
            inValue.keyPass = keyPass;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).cancelarConOpcionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbradoBase64Prueba(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest request) {
            return base.Channel.timbradoBase64Prueba(request);
        }
        
        public string timbradoBase64Prueba(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXmlBase64 = cfdiXmlBase64;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbradoBase64Prueba(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbradoBase64PruebaAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest request) {
            return base.Channel.timbradoBase64PruebaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaResponse> timbradoBase64PruebaAsync(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64PruebaRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXmlBase64 = cfdiXmlBase64;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbradoBase64PruebaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesResponse UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.consultarPeticionesPendientes(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest request) {
            return base.Channel.consultarPeticionesPendientes(request);
        }
        
        public string consultarPeticionesPendientes(string contrato, string usuario, string passwd, string rfcReceptor, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcReceptor = rfcReceptor;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesResponse retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).consultarPeticionesPendientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesResponse> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.consultarPeticionesPendientesAsync(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest request) {
            return base.Channel.consultarPeticionesPendientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesResponse> consultarPeticionesPendientesAsync(string contrato, string usuario, string passwd, string rfcReceptor, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.consultarPeticionesPendientesRequest();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.rfcReceptor = rfcReceptor;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).consultarPeticionesPendientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Response UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbradoBase64(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request request) {
            return base.Channel.timbradoBase64(request);
        }
        
        public string timbradoBase64(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXmlBase64 = cfdiXmlBase64;
            inValue.opciones = opciones;
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Response retVal = ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbradoBase64(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Response> UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService.timbradoBase64Async(UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request request) {
            return base.Channel.timbradoBase64Async(request);
        }
        
        public System.Threading.Tasks.Task<UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Response> timbradoBase64Async(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request inValue = new UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.timbradoBase64Request();
            inValue.contrato = contrato;
            inValue.usuario = usuario;
            inValue.passwd = passwd;
            inValue.cfdiXmlBase64 = cfdiXmlBase64;
            inValue.opciones = opciones;
            return ((UGRS.AddOn.Purchases.TimbradoSoap33Prodigia.PadeTimbradoService)(this)).timbradoBase64Async(inValue);
        }
    }
}
